### ISSUE TITLE
freezes if sleep session started from phone

### ISSUE THREAD

**Issue by switch87** [urbandroid-team/Sleep-as-Android-Garmin-Addon#4]
The app freezes my watch if the session is started from the phone. I have a vivoactive HR. The problem also hapens on other Garmin devices according to reviews on Connect IQ.

[Reviews on IQ](https://apps.garmin.com/nl-BE/apps/e80a4793-f5a3-44c7-bd7f-52a97f5d8310;jsessionid=1E99FF7CEB5F769F726457B4B50ABBA8?tab=reviews&displayCurrentVersion=true)

**Comment by ploum** [comment]
On my Descent MK1, it seems to "freeze" the watch (well, the application cannot be quit without rebooting the watch), even if I start from the phone. 

It doesn't happen all the time. It looks more like the watch loosing connection with the phone and then continuing the app without a way for the user to quit the app.

**Comment by aaronjwood** [comment]
Have you guys tried the latest version? It seems that most things are fixed. I was never able to get this to work properly on my Fenix 5 until they released the new version at the end of August.

**Comment by switch87** [comment]
I started using it again since yesterday, new version looks better and the first use did go smooth. To bad the developers do not take the time to answer or inform us ...

**Comment by Artaud** [comment]
Hi all, thanks for letting us know your feedback.  I was thinking that an update on the watch would be enough, but from what you say I'm thinking a notice in the main app would be much better. Thanks for the tip, we're going to do that in the next release.

**Comment by sitaramp** [comment]
This happen on Forerunner 235 with the version 20180918
The screen remains stuck with a message "Starting ..." .
The phone app status shows that the watch is connected, but no data is collected.
The only way to get out of stuck message is to reboot the watch.
Changing to  default garmin watchface makes no difference.

**Comment by switch87** [comment]
On vivoactive hr it also still crashes, stops registration in the middle of the night. I could only use the new version for 1 night without having problems.

**Comment by Artaud** [comment]
> This happen on Forerunner 235 with the version 20180918
> The screen remains stuck with a message "Starting ..." .
> The phone app status shows that the watch is connected, but no data is collected.
> The only way to get out of stuck message is to reboot the watch.
> Changing to default garmin watchface makes no difference.

Could you please send me a debug log (menu > send wearable report in Sleep as Android)?

**Comment by sitaramp** [comment]
This has been resolved on Forerunner 235 with the version 20181128. Thanks
